def run() {
    node {
        stage("Hello World...") {
            script {
                def helloWorld = "Welcome!! This is my new message!!!"
                echo "${helloWorld}"
            }
        }
    }
}

return this
